pipeline {
    agent any
    stages {
        stage('Run tests') {
            steps {
                bat 'pip install pytest'
                bat 'pytest --junitxml=pytest_report.xml'
            }
        }
    }
    post {
        always {
            junit 'pytest_report.xml'
        }
    }
}
